### ISSUE TITLE
Dataset EndDate filter : condition is on StartDate

### ISSUE THREAD

**Issue by going-striker** [paranoidTwitch/Reckdl#2]
Hi

First of all, thanks for the work.
I'm working using Quandl data and tried your project vs Quandl.NET cuz I like the fact there is almost no dependency.

That being said, there is a bug in dataset filters, in the ProcessFilter method
Copy / paste error as you make a condition on StartDate while treating EndDate
That makes a "Nullable filter must have a value" exception when using EndDate filter.

```
            if (options.StartDate.HasValue)
            {
                filterAdditions.Add($"end_date={options.EndDate**.Value.ToString("yyyy-MM-dd")}");
            }
```
Shoudn't take more than 30 secs to fix.

I can contribute if you want but a little later as I can't upload from my current station.

Best regards

**Comment by going-striker** [comment]
Did it today : https://github.com/paranoidTwitch/Reckdl/pull/3

**Comment by paranoidTwitch** [comment]
Hey, sorry it took me a bit to get to this. Don't get on here every day. Thanks for the PR. I'll check it out and pull it in. I'll need to update the nuget packages as well so the fix propagates. I'll close this issue out once that is done. 

Since you are using this, I'm going to convert this to net standard at some point in the near future. Are there any features or anything along those lines you would like to see?

**Comment by paranoidTwitch** [comment]
Nuget.org has been updated. The package should be available shortly. Let me know if you have any more issues with this item.

**Comment by going-striker** [comment]
Thanks for the release. I'll delete my fork then.

Not that I can think of as of now. My calls are quite simple and so far so good :)

**Comment by paranoidTwitch** [comment]
Cool, I've moved this to .NET Standard 2.0 so the maintenance is not a nightmare. Since its a super breaking change and I'm not super fan of how this is named, I've moved the repo here: 

https://github.com/paranoidTwitch/DotNetConnect.Quandl 

Ill leave this project up but future maintenance is going to be on the new project.
